suorganizer/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import PostList, post_detail, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth


urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',PostArchiveMonth.as_view(), name='post_archive_month'),

    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$', post_detail, name='post_detail'),

    url(r'^create/$', PostCreate.as_view(), name='post_form_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
    ]

suorganizer/suorganizer/urls.py
"""
Definition of urls for suorganizer.
"""

from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.contrib import admin, auth
from django.contrib.auth import urls as auth_urls
from django.contrib.flatpages import urls as flatpages_urls
from .views import redirect_root
# admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', suorganizer.views.home, name='home'),
    # url(r'^suorganizer/', include('suorganizer.suorganizer.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', app_name='user', namespace='dj-auth')),
    url(r'^$', RedirectView.as_view(pattern_name='blog:post_list',permanent=False)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^contact/', include('contact.urls')),
    #url(r'^page/', include(flatpages_urls)),
    url(r'^', include('organizer.urls', namespace='organizer', app_name='organizer')),
    url(r'^', include(flatpages_urls)),
]

suorganizer/user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

from .views import DisableAccount, ActivateAccount, CreateAccount, ProfileDetail, ProfileUpdate, PublicProfileDetail

'''
url(r'^password/', include(password_urls)),
'''


password_urls = [
    # 修改密码
    url(r'^change/$',
        auth_views.password_change,
        # 替换默认的模板文件
        {'template_name': 'user/password_change_form.html',
        # 在url中需要用reverse_lazy
         'post_change_redirect': reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),

    # 重置密码
     url(r'^reset/$', auth_views.password_reset,
        {'template_name': 'user/password_reset_form.html',
         'email_template_name': 'user/password_reset_email.txt',
         'subject_template_name': 'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy( 'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
     url(r'^reset/sent/$', auth_views.password_reset_done,
        {'template_name': 'user/password_reset_sent.html'},
        name='pw_reset_sent'),
     url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm,
        {'template_name': 'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy( 'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
     url(r'reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'user/password_reset_complete.html',
        # To immediately allow them to log in
         'extra_context': {'form': AuthenticationForm}},
        name='pw_reset_complete'),
     url(r'^$', RedirectView.as_view(pattern_name='dj-auth:pw_reset_start', permanent=False)),
]






urlpatterns = [
    url(r'^login/$', auth_views.login, {
            'template_name': 'user/login.html'
            }, name='login'),
    # Add AuthenticationForm to the context 
    # of the logged_out.html template
    url(r'^logout/$', auth_views.logout, {
            'template_name': 'user/logged_out.html', 
            'extra_context': {'form': AuthenticationForm}
            }, name='logout'),
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^password/', include(password_urls)),
    url(r'^disable/$',DisableAccount.as_view(),name='disable'),
    url(r'^create/$',CreateAccount.as_view(),name='create'),
    url(r'^create/done/$',TemplateView.as_view(template_name='user/user_create_done.html'),name='create_done'),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',ActivateAccount.as_view(),name='activate'),
    url(r'^profile/$', ProfileDetail.as_view(), name='profile'),
    url(r'^profile/edit/$',ProfileUpdate.as_view(),name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',PublicProfileDetail.as_view(),name='public_profile'),

]

suorganizer/user/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

class Profile(models.Model):
    #By default, the AUTH_USER_MODEL setting points to auth.User
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=255)
    joined = models.DateTimeField("Date Joined", auto_now_add=True)
    slug = models.SlugField(max_length=30, unique=True)
    about = models.TextField()

    def __str__(self):
        return self.user.get_username()

    def get_update_url(self):
        return reverse('dj-auth:profile_update')

    def get_absolute_url(self): 
        return reverse('dj-auth:public_profile', kwargs={'slug': self.slug})


class UserManager(BaseUserManager):
    # Let migrations system use the manager when interacting with User
    use_in_migrations = True

    def _create_user(self, email, password, **kwargs):
        email           = self.normalize_email(email)
        is_staff        = kwargs.pop('is_staff', False)
        is_superuser    = kwargs.pop('is_superuser', False)
        user            = self.model(email=email, is_active=True, is_staff=is_staff, is_superuser=is_superuser, **kwargs)
        user.set_password(password)
        user.save(using =self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, is_staff=True, is_superuser=True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email          = models.EmailField('email address', max_length=254, unique=True)
    is_staff       = models.BooleanField('staff status', default=False, help_text=('Designates whether the user can log into this admin site.'))
    is_active      = models.BooleanField('active', default=True, help_text=('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    # informs Django which of our fields is to be used for logins and the like
    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return self.profile.get_absolute_url()

    def get_full_name(self):
        return self.profile.name

    def get_short_name(self):
        return self.profile.name

suorganizer/user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm

from .utils import ActivationMailFormMixin


class UserCreationForm(ActivationMailFormMixin, BaseUserCreationForm):

    mail_validation_error = 'User created. Could not send activation email. Please try again later. (Sorry!)'

    class Meta(BaseUserCreationForm.Meta):
        model = get_user_model()  # overriding the model
        fields = ('username', 'email')  # adding the email form to the field


    def clean_username(self):
        username = self.cleaned_data['username']
        disallowed = ('activate', 'create', 'disable', 'login', 
                      'logout', 'password', 'profile')
        if username in disallowed:
            raise ValidationError( "A user with that username already exists.")
        return username


    def save(self, **kwargs):
        user = super().save(commit=False)
        if not user.pk:  # 数据库中尚不存在该用户
            user.is_active = False
            send_mail = True
        else:
            send_mail = False
        user.save()
        # save any many-to-many relations using the save_m2m() method
        self.save_m2m()
        # We want Profile instances to be created at the same time as User accounts
        Profile.objects.update_or_create(user=user,
            defaults={
                'slug': slugify(user.get_username()),
            })
        if send_mail:
            self.send_mail(user=user, **kwargs)
        return user

suorganizer/user/views.py
from django.conf import settings
from django.contrib.auth import get_user, logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.decorators import method_decorator
from django.contrib.messages import error, success
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.views.generic import View, DetailView
from django.core.urlresolvers import reverse_lazy
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.debug import sensitive_post_parameters

from .forms import UserCreationForm
from .utils import MailContextViewMixin, ProfileGetObjectMixin
from .decorators import class_login_required
from .models import Profile
from core.utils import UpdateView


class DisableAccount(View):
    success_url = settings.LOGIN_REDIRECT_URL
    template_name = 'user/user_confirm_delete.html'

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def get(self, request):
        # a replacement for the HttpResponse object
        return TemplateResponse(request, self.template_name)

    @method_decorator(csrf_protect)
    @method_decorator(login_required)
    def post(self, request):
        #The get_user() function takes an HttpRequest object 
        #and returns the User (or AnonymousUser) instance.
        user = get_user(request)
        # Disable the user
        user.set_unusable_password()
        user.is_active = False
        user.save()
        # destroy the current user’s session to log the user out
        logout(request)
        return redirect(self.success_url)



class CreateAccount(MailContextViewMixin, View):
    form_class = UserCreationForm
    success_url = reverse_lazy('dj-auth:create_done')
    template_name = 'user/user_create.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(request, self.template_name, {'form': self.form_class()})

    @method_decorator(csrf_protect)  # marks specific data as sensitive
    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            # not catching returned user
            bound_form.save(**self.get_save_kwargs(request))
            if bound_form.mail_sent:  # mail sent?
                return redirect(self.success_url)
            else:
                errs = bound_form.non_field_errors()
                for err in errs:
                    error(request, err)
                # TODO: redirect to email resend
        return TemplateResponse(request, self.template_name, {'form': bound_form})



class ActivateAccount(View):
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/user_activate.html'

    @method_decorator(never_cache)
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            # turn the base-64 uidb64 number into a base-10 number
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        if (user is not None and token_generator.check_token(user, token)):
            user.is_active = True
            user.save()
            success(request, 'User Activated! You may now login.')
            return redirect(self.success_url)
        else:
            return TemplateResponse(request, self.template_name)

@class_login_required
class ProfileDetail(ProfileGetObjectMixin, DetailView):
    model = Profile


class PublicProfileDetail(DetailView):
    model = Profile


@class_login_required
class ProfileUpdate(ProfileGetObjectMixin, UpdateView):
    # The view will generate a form for us using ModelForm inheritance
    fields = ('about',)
    model = Profile

suorganizer/user/templates/user/base_user.html
{% extends parent_template|default:"base.html" %}

suorganizer/user/templates/user/logged_out.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Logged Out
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>You've successfully logged out.</p>
      {% include "user/login_form.html" with login_button='Log Back In' %}
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/login.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Login
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two five columns">
      {% include "user/login_form.html" %}
    </div>
    <div class="three columns">
      <ul class="task-list">
        <li><a href="{% url 'dj-auth:create' %}">Register New Account</a></li>
        <li><a href="{% url 'dj-auth:pw_reset_start' %}">Forgotten password?</a></li>
      </ul>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/login_form.html
<form action="{% url 'dj-auth:login' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  {% if next %}
    {#REDIRECT_FIELD_NAME = 'next'#}
    <input type="hidden" name="next" value="{{ next }}"> 
  {% endif %}
  <button type="submit">{{ login_button|default:'Log in' }}</button>
</form>

suorganizer/user/templates/user/password_change_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>Password successfully changed.</p>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/password_change_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Change Password
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">

      <form action="{% url 'dj-auth:pw_change' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change Password</button>
      </form>

    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/password_reset_form.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Reset Password
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <div class="center">
        <p>Reset your password by email.</p>
      </div>
      <form action="{% url 'dj-auth:pw_reset_start' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send Me Reset Instructions</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/password_reset_sent.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Password Reset Sent
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>Password reset email sent!</p>
      <p>Please check your inbox and spam box.</p>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/profile_detail.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - {{ profile.user.get_username }}'s Profile
{% endblock %}

{% block content %}
  <div class="row">
      <div class="offset-by-two five columns">
        <h2>About {{ profile.user.get_username }}</h2>
        {{ profile.about|default:"No Profile"|linebreaks }}
      </div><!-- columns -->
      {% if user.pk == profile.user.pk %}
      <div class="three columns">
        <ul class="task-list">
          <li><a href="{{ profile.get_update_url }}">Edit Your Profile</a></li>
          <li><a href="{% url 'dj-auth:pw_change' %}">Change Password</a></li>
          <li><a href="{% url 'dj-auth:disable' %}">Disable Account</a></li>
        </ul>
      </div>
      {% endif %}

  </div><!-- row -->
{% endblock %}

suorganizer/user/templates/user/profile_form_update.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Update Profile
{% endblock %}


{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form action="{{ profile.get_update_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Profile</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/user_activate.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Account Activation Failed
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>This activation link is no longer valid.</p>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/user_create.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Create Account
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form action="{% url 'dj-auth:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create New Account</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/user/templates/user/user_create_done.html
{% extends parent_template|default:"user/base_user.html" %}

{% block title %}
{{ block.super }} - Account Created
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <p>Your account has been created!</p>
      <p>Please check your email for the activation link.</p>
    </div>
  </div>
{% endblock %}