suorganizer/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import PostList, post_detail, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth


urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',PostArchiveMonth.as_view(), name='post_archive_month'),

    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$', post_detail, name='post_detail'),

    url(r'^create/$', PostCreate.as_view(), name='post_form_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
    ]

suorganizer/suorganizer/urls.py
"""
Definition of urls for suorganizer.
"""

from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.contrib import admin, auth
from django.contrib.auth import urls as auth_urls
from django.contrib.flatpages import urls as flatpages_urls
from .views import redirect_root
# admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', suorganizer.views.home, name='home'),
    # url(r'^suorganizer/', include('suorganizer.suorganizer.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', app_name='user', namespace='dj-auth')),
    url(r'^$', RedirectView.as_view(pattern_name='blog:post_list',permanent=False)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^contact/', include('contact.urls')),
    #url(r'^page/', include(flatpages_urls)),
    url(r'^', include('organizer.urls', namespace='organizer', app_name='organizer')),
    url(r'^', include(flatpages_urls)),
]

suorganizer/blog/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import Group
from organizer.models import Startup, Tag


class Post(models.Model):
    title    = models.CharField(max_length=63)
    slug     = models.SlugField(max_length=63, help_text='A label for URL config', unique_for_month='pub_date')
    text     = models.TextField()
    pub_date = models.DateField(verbose_name='date published', auto_now_add=True)
    
    tags     = models.ManyToManyField(Tag, related_name='blog_posts')
    startups = models.ManyToManyField(Startup, related_name='blog_posts')

    def __str__(self):
        return "{} on {}".format(self.title, self.pub_date.strftime('%Y-%m-%d'))

    class Meta:
        verbose_name  = 'blog post'
        ordering      = ['-pub_date', 'title']
        get_latest_by = 'pub_date'
        permissions = [
            ("view_future_post", "Can view unpublished Post"),
        ]

    def get_absolute_url(self):
        return reverse('blog:post_detail', 
                       kwargs={'year' : self.pub_date.year, 
                               'month': self.pub_date.month,
                               'slug' : self.slug})

    def get_update_url(self):
        return reverse('blog:post_update',
                       kwargs={'year' : self.pub_date.year, 
                               'month': self.pub_date.month,
                               'slug' : self.slug})

    def get_delete_url(self):
        return reverse('blog:post_delete',
                       kwargs={'year' : self.pub_date.year, 
                               'month': self.pub_date.month,
                               'slug' : self.slug})

    def get_archive_year_url(self):
        return reverse('blog_post_archive_year', kwargs={'year': self.pub_date.year})

    def get_archive_month_url(self):
        return reverse('blog_post_archive_month', kwargs={
            'year': self.pub_date.year, 
            'month': self.pub_date.month
            })

suorganizer/blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

suorganizer/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods
from django.views.generic import View, CreateView, ListView, YearArchiveView, MonthArchiveView, ArchiveIndexView

from user.decorators import require_authenticated_permission

from .models import Post
from .forms import PostForm
from .utils import AllowFuturePermissionMixin

@require_http_methods(['HEAD', 'GET'])
def post_detail(request, year, month, slug):
    post = get_object_or_404(Post, 
                             pub_date__year=year, pub_date__month=month, slug=slug)
    return render(request, 
                  'blog/post_detail.html',
                  {'post': post})


#class PostList(ListView):
#    model = Post
    #def get(self, request):
    #    return render(request, 
    #                  'blog/post_list.html',
    #                  {'post_list': Post.objects.all()})
class PostList(AllowFuturePermissionMixin, ArchiveIndexView):
    allow_empty = True
    #allow_future = True 默认为False
    context_object_name = 'post_list'
    date_field = 'pub_date'
    make_object_list = True
    model = Post
    paginate_by = 5
    template_name = 'blog/post_list.html'


@require_authenticated_permission('blog.add_post')
class PostCreate(CreateView):
    form_class = PostForm
    template_name = 'blog/post_form_create.html'

    #def get(self, request):
    #    return render(request, 
    #                  self.template_name, 
    #                  {'form': self.form_class()})

    #def post(self, request):
    #    bound_form = self.form_class(request.POST)
    #    if bound_form.is_valid():
    #        new_post = bound_form.save()
    #        return redirect(new_post)
    #    else:
    #        return render(request,
    #                      self.template_name,
    #                      {'form': bound_form})


class PostUpdate(View):
    # why:为什么这样能实现博客的修改而非新增?
    form_class = PostForm
    model = Post
    template_name = 'blog/post_form_update.html'

    def get(self, request, year, month, slug):
        post = get_object_or_404(self.model, 
                                 pub_date__year=year, pub_date__month=month, slug=slug)
        return render(request,
                      self.template_name,
                      {'form': self.form_class(instance=post), 'post': post})

    def post(self, request, year, month, slug):
        post = get_object_or_404(self.model, 
                                 pub_date__year=year, pub_date__month=month, slug=slug)
        # 这里的instance=post是实现博客的修改而非新增的关键
        bound_form = self.form_class(request.POST, instance=post)
        if bound_form.is_valid():
            new_post = bound_form.save()
            return redirect(new_post)
        else:
            return render(request,
                          self.template_name,
                          {'form': bound_form, 'post': post})


class PostDelete(View):
    model = Post
    template_name = 'blog/post_form_delete.html'

    def get(self, request, year, month, slug):
        post = get_object_or_404(self.model, 
                                 pub_date__year=year, pub_date__month=month, slug=slug)
        return render(request, self.template_name, {'post': post})

    def post(self, request, year, month, slug):
        post = get_object_or_404(self.model, 
                                 pub_date__year=year, pub_date__month=month, slug=slug)
        post.delete()
        return redirect('blog:post_list')


class PostArchiveYear(YearArchiveView):
    model = Post
    date_field = 'pub_date'
    make_object_list  = True


class PostArchiveMonth(MonthArchiveView):
    model = Post
    date_field = 'pub_date'
    month_format = '%m'

suorganizer/blog/templates/blog/base_blog.html
{% extends parent_template|default:"base.html" %}

{% load staticfiles %}
{% block head %}
    <link href="{% static 'blog/style.css' %}" rel="stylesheet" />
{% endblock %}

suorganizer/blog/templates/blog/post_archive_month.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - {{ month|date:"F Y" }} Posts
{% endblock %}

{% block content %}
<div class="row">
  <div class="eight columns">
    <div class="mobile">
        <a href="{% url 'blog:post_form_create' %}" class="button button-primary">Write New Blog Post</a>
    </div>
    <h2>All Posts for {{ month|date:"F Y" }}</h2>
    {% for post in post_list %}
      <article class="list-item">
        <header>
          <h3>
            <a href="{{ post.get_absolute_url }}">
              {{ post.title|title }}
          </a></h3>
            <ul class="inline">
                <li> <a href="{{ post.get_update_url }}" class="button">Edit Post</a></li>
                <li> <a href="{{ post.get_delete_url }}" class="button"> Delete Post</a></li>
            </ul>
          <p>
            Written on: <time datetime="{{ post.pub_date|date:"Y-m-d" }}"> {{ post.pub_date|date:"l, F j, Y" }}</time>
          </p>
        </header>
        <p>{{ post.text|truncatewords:20 }}</p>
        <p class="read-more"> <a href="{{ post.get_absolute_url }}"> Read more…</a></p>
      </article>
    {% endfor %}
  </div><!-- eight columns -->
  <div class="desktop four columns">
    <a href="{% url 'blog:post_form_create' %}" class="button button-primary"> Write New Blog Post</a>
    <p><a href="{% url 'blog:post_archive_year' month|date:"Y" %}">All Posts from {{ month|date:"Y" }}</a></p>
    <p><a href="{% url 'blog:post_list' %}">Latest Posts</a></p>
  </div><!-- four columns -->
</div><!-- row -->
<div class="row">
  <div class="twelve columns">
    <ul class="pagination">
      {% if previous_month %}
        <li>
          <a href="{% url 'blog:post_archive_month' previous_month|date:"Y" previous_month|date:"m" %}">
            ◀︎ Posts from {{ previous_month|date:"F Y" }}</a>
        </li>
      {% endif %}
      {% if next_month %}
        <li>
          <a href="{% url 'blog:post_archive_month' next_month|date:"Y" next_month|date:"m" %}">
            Posts from {{ next_month|date:"F Y" }} ▶︎</a>
        </li>
      {% endif %}
    </ul>
  </div>
</div>
{% endblock %}

suorganizer/blog/templates/blog/post_archive_year.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
{{ block.super }} - {{ year|date:"Y" }} Posts
{% endblock %}

{% block content %}
<div class="row">
  <div class="eight columns">
    <div class="mobile">
        <a href="{% url 'blog:post_form_create' %}" class="button button-primary">Write New Blog Post</a>
    </div>
    <h2>All Posts for {{ year|date:"Y" }}</h2>

    {% for post in post_list %}
      <article class="list-item">
        <header>
          <h3> <a href="{{ post.get_absolute_url }}"> {{ post.title|title }} </a></h3>
            <ul class="inline">
                <li>
                  <a href="{{ post.get_update_url }}" class="button"> Edit Post</a></li>
                <li>
                  <a href="{{ post.get_delete_url }}" class="button"> Delete Post</a></li>
            </ul>
          <p>
            Written on: <time datetime="{{ post.pub_date|date:"Y-m-d" }}"> {{ post.pub_date|date:"l, F j, Y" }} </time>
          </p>
        </header>

        <p>{{ post.text|truncatewords:20 }}</p>
        <p class="read-more"> <a href="{{ post.get_absolute_url }}"> Read more&hellip; </a><p>
      </article>
    {% endfor %}
  </div>

  <div class="desktop four columns">
      <a href="{% url 'blog:post_form_create' %}" class="button button-primary"> Write New Blog Post</a>
    <h3>Archives by Month</h3>
    <ul>
      {% for m in date_list %}
        <li><a href="{% url 'blog:post_archive_month' m|date:"Y" m|date:"n" %}">{{ m|date:"F Y" }}</a></li>
      {% endfor %}
    </ul>
  </div>

</div>
<div class="row">
  <div class="twelve columns">
    <ul class="pagination">
      {% if previous_year %}
        <li>
          <a href="{% url 'blog:post_archive_year' previous_year|date:"Y" %}">
            ❮ Posts from {{ previous_year|date:"Y" }}</a>
        </li>
      {% endif %}
      {% if next_year %}
        <li>
          <a href="{% url 'blog:post_archive_year' next_year|date:"Y" %}">
            Posts from {{ next_year|date:"Y" }} ❯</a>
        </li>
      {% endif %}
    </ul>
  </div>
</div>
{% endblock %}

suorganizer/blog/templates/blog/post_detail.html
{% extends parent_template|default:"blog/base_blog.html" %}{#post|form#}

{% block title %}
    {{ block.super }} - {{ post.title|title }}
{% endblock %}

{% block content %}
    <article>
        <header>
            {#博客文章开头部分#}
            <h2>{{ post.title|title }}</h2>
            <ul>
                <li><a href="{{ post.get_update_url }}">Edit Post</a></li>
            </ul>
            <p>
                Written on <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                {{ post.pub_date|date:"l, F j, Y"}}</time>
            </p>
        </header>
        {#正文#}
        {{ post.text|linebreaks }}

        {% if post.startups.all or post.tags.all %}
            {#在博客文章结尾展示对应机构和标签信息#}
            <footer>
                {% if post.startups.all %}
                    <section>
                        <h3>Startup{{ post.startups.count|pluralize }}</h3>
                        <ul>
                            {% for startup in post.startups.all %}
                                <li><a href="{{ startup.get_absolute_url }}">{{ startup.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </section>
                {% endif %}

                {% if post.tags.all %}
                    <section>
                        <h3>Tag{{ post.tags.count|pluralize }}</h3>
                        <ul>
                            {% for tag in post.tags.all %}
                                <li><a href="{{ tag.get_absolute_url }}">{{ tag.name|title }}</a></li>
                            {% endfor %}
                        </ul>
                    </section>
                {% endif %}
            </footer>
        {% endif %}
    </article>
{% endblock %}

suorganizer/blog/templates/blog/post_form_create.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - Create Blog Post
{% endblock %}

{% block content %}
    <div>
        <div>
            {# action应该可以为""吧, 毕竟提交表单和展示表单都是同一个url #}
            <form action="{% url 'blog:post_form_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Blog Post</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/blog/templates/blog/post_form_delete.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - Delete Blog Post
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ post.get_delete_url }}" method="post">
                {% csrf_token %}
                <p>
                  Are you sure you want to delete the blog post titled {{ post.title }}?
                </p>
                <a href="{{ post.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete Blog Post</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/blog/templates/blog/post_form_update.html
{% extends parent_template|default:"blog/base_blog.html" %} {#post|form#}

{% block title %}
    {{ block.super }} - Update Blog Post
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ post.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Blog Post</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/blog/templates/blog/post_list.html
{% extends parent_template|default:"blog/base_blog.html" %}

{% block title %}
    {{ block.super }} - Blog
{% endblock %}

{% block content %}
<div class="row">
    <div class="eight columns">
    <div>
        <a href="{% url 'blog:post_form_create' %}">Write New Blog Post</a>
    </div>
    {% for post in post_list %}
        <article>
            <header>
                {#博客文章开头部分#}
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></h2>
                <ul>
                    <li><a href="{{ post.get_update_url }}">Edit Post</a></li>
                    <li><a href="{{ post.get_delete_url }}">Delete Post</a></li>
                </ul>
                <p>
                    Written on: <time datetime="{{ post.pub_date|date:"Y-m-d" }}">
                    {{ post.pub_date|date:"l, F j, Y"}}</time>
                </p>
            </header>
            {#正文节选#}
            <p>{{ post.text|truncatewords:20}}</p>
            <p><a href="{{ post.get_absolute_url }}">Read more&hellip;</a></p>
        </article>
    {% empty %}
        <p><em>No Blog Posts Available</em></p>
    {% endfor %}
    </div>
    <div class="desktop four columns">
      <a href="{% url 'blog:post_form_create' %}" class="button button-primary"> Write New Blog Post</a>
      <h3>Post Archives</h3>
      <ul>
        {% for y in date_list %}
          <li><a href="{% url 'blog:post_archive_year' y|date:"Y" %}">
            {{ y|date:"Y" }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}