suorganizer/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import PostList, post_detail, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth


urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',PostArchiveMonth.as_view(), name='post_archive_month'),

    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$', post_detail, name='post_detail'),

    url(r'^create/$', PostCreate.as_view(), name='post_form_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
    ]

suorganizer/organizer/urls.py
from django.conf.urls import url


from .views import (StartupDetail, StartupList, 
                    TagDetail, TagList, TagPageList,
                    TagCreate, StartupCreate, NewsLinkCreate,
                    TagUpdate, StartupUpdate, NewsLinkUpdate,
                    TagDelete, StartupDelete, NewsLinkDelete,)


urlpatterns = [
    url(r'^newslink/create/$', NewsLinkCreate.as_view(), name='newslink_create' ),
    url(r'^newslink/update/(?P<pk>\d+)/$', NewsLinkUpdate.as_view(), name='newslink_update'),
    url(r'^newslink/delete/(?P<pk>\d+)/$', NewsLinkDelete.as_view(), name='newslink_delete'),

    url(r'^startup/$', StartupList.as_view(), name='startup_list'),
    url(r'^startup/create/$', StartupCreate.as_view(), name='startup_form_create'),
    url(r'^startup/(?P<slug>[\w\-]+)/$', StartupDetail.as_view(), name='startup_detail'),
    url(r'^startup/(?P<slug>[\w\-]+)/update/$', StartupUpdate.as_view(), name='startup_update'),
    url(r'^startup/(?P<slug>[\w\-]+)/delete/$', StartupDelete.as_view(), name='startup_delete'),

    url(r'^tag/$', TagList.as_view(), name='tag_list'),
    url(r'^tag/(?P<page_number>\d+)/$', TagPageList.as_view(), name='tag_page'),
    url(r'^tag/create/$', TagCreate.as_view(), name='tag_form_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', TagDetail.as_view(), name='tag_detail'),
    url(r'^tag/(?P<slug>[\w\-]+)/update/$', TagUpdate.as_view(), name='tag_update'),
    url(r'^tag/(?P<slug>[\w\-]+)/delete/$', TagDelete.as_view(), name='tag_delete'),
]

suorganizer/suorganizer/urls.py
"""
Definition of urls for suorganizer.
"""

from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.contrib import admin, auth
from django.contrib.auth import urls as auth_urls
from django.contrib.flatpages import urls as flatpages_urls
from .views import redirect_root
# admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', suorganizer.views.home, name='home'),
    # url(r'^suorganizer/', include('suorganizer.suorganizer.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', app_name='user', namespace='dj-auth')),
    url(r'^$', RedirectView.as_view(pattern_name='blog:post_list',permanent=False)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^contact/', include('contact.urls')),
    #url(r'^page/', include(flatpages_urls)),
    url(r'^', include('organizer.urls', namespace='organizer', app_name='organizer')),
    url(r'^', include(flatpages_urls)),
]

suorganizer/user/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView, TemplateView

from .views import DisableAccount, ActivateAccount, CreateAccount, ProfileDetail, ProfileUpdate, PublicProfileDetail

'''
url(r'^password/', include(password_urls)),
'''


password_urls = [
    # 修改密码
    url(r'^change/$',
        auth_views.password_change,
        # 替换默认的模板文件
        {'template_name': 'user/password_change_form.html',
        # 在url中需要用reverse_lazy
         'post_change_redirect': reverse_lazy('dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name': 'user/password_change_done.html'},
        name='pw_change_done'),

    # 重置密码
     url(r'^reset/$', auth_views.password_reset,
        {'template_name': 'user/password_reset_form.html',
         'email_template_name': 'user/password_reset_email.txt',
         'subject_template_name': 'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy( 'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
     url(r'^reset/sent/$', auth_views.password_reset_done,
        {'template_name': 'user/password_reset_sent.html'},
        name='pw_reset_sent'),
     url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm,
        {'template_name': 'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy( 'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
     url(r'reset/done/$', auth_views.password_reset_complete,
        {'template_name': 'user/password_reset_complete.html',
        # To immediately allow them to log in
         'extra_context': {'form': AuthenticationForm}},
        name='pw_reset_complete'),
     url(r'^$', RedirectView.as_view(pattern_name='dj-auth:pw_reset_start', permanent=False)),
]






urlpatterns = [
    url(r'^login/$', auth_views.login, {
            'template_name': 'user/login.html'
            }, name='login'),
    # Add AuthenticationForm to the context 
    # of the logged_out.html template
    url(r'^logout/$', auth_views.logout, {
            'template_name': 'user/logged_out.html', 
            'extra_context': {'form': AuthenticationForm}
            }, name='logout'),
    url(r'^$', RedirectView.as_view(pattern_name='dj-auth:login', permanent=False)),
    url(r'^password/', include(password_urls)),
    url(r'^disable/$',DisableAccount.as_view(),name='disable'),
    url(r'^create/$',CreateAccount.as_view(),name='create'),
    url(r'^create/done/$',TemplateView.as_view(template_name='user/user_create_done.html'),name='create_done'),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',ActivateAccount.as_view(),name='activate'),
    url(r'^profile/$', ProfileDetail.as_view(), name='profile'),
    url(r'^profile/edit/$',ProfileUpdate.as_view(),name='profile_update'),
    url(r'^(?P<slug>[\w\-]+)/$',PublicProfileDetail.as_view(),name='public_profile'),

]

suorganizer/templates/base.html
{% load staticfiles %}
{% load flatpages %}
{# We can call get_flatpages and set all of the #} 
{# FlatPage objects as the flatpages variable #}
{% get_flatpages as flatpages %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
            Startup Organizer
        {% endblock %}
    </title>
    <link href="{% static 'site/normalize.css' %}" rel="stylesheet" />
    <link href="{% static 'site/skeleton.css' %}" rel="stylesheet" />
    <link href="{% static 'site/style.css' %}" rel="stylesheet" />
    {% block head %}{% endblock %}
</head>
<body>
    <div class="container">

        <div class="status row">
        <div class="offset-by-eight four columns">
          <ul class="inline">
            {% if user.is_authenticated %}
              <li><a href="{% url 'dj-auth:profile' %}">View Profile</a></li>
              <li><a href="{% url 'dj-auth:logout' %}?next={{ request.path }}">Log Out</a></li>
            {% else %}
              <li><a href="{% url 'dj-auth:create' %}">Register</a></li>
              <li><a href="{% url 'dj-auth:login' %}?next={{ request.path }}">Log In</a></li>
            {% endif %}
          </ul>
        </div>
        </div>

        <header class="row">
            <img src="{% static 'site/logo.png' %}" alt="Site Logo" />
            <h1 class="logo">Startup Organizer</h1>
        </header>
        <nav>
            <ul>
                <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
                <li><a href="{% url 'organizer:startup_list' %}">Startups</a></li>
                <li><a href="{% url 'organizer:tag_list' %}">Tags</a></li>
                <li><a href="{% url 'contact' %}">Contact</a></li>
                {% for each in flatpages %}
                    <li><a href="{{ each.get_absolute_url }}">{{ each.title }}</a></li>
                {% endfor %}

            </ul>
        </nav>

        {% if messages %}
        <div>
          <div>
            <ul>
              {% for message in messages %}
                {% if message.tags %}
                  <li class="{{ message.tags }}">
                {% else %}
                  <li>
                {% endif %}
                {{ message }}</li>
              {% endfor %}
            </ul>
           </div>
        </div>
        {% endif %}

        <main>
            {% block content %}
                This is default content!
            {% endblock %}
        </main>
    </div>
    <footer>
        <p>
            &copy;2015 <a href="">Andrew Pinkham</a>
        </p>
        <p>
            Created for <a href="">Django Unleashed</a>
        </p>
    </footer>
</body>
</html>