suorganizer/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import PostList, post_detail, PostCreate, PostUpdate, PostDelete, PostArchiveYear, PostArchiveMonth


urlpatterns = [
    url(r'^$', PostList.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/$', PostArchiveYear.as_view(), name='post_archive_year'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{1,2})/$',PostArchiveMonth.as_view(), name='post_archive_month'),

    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/$', post_detail, name='post_detail'),

    url(r'^create/$', PostCreate.as_view(), name='post_form_create'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/update/$', PostUpdate.as_view(), name='post_update'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/delete/$', PostDelete.as_view(), name='post_delete'),
    ]

suorganizer/organizer/urls.py
from django.conf.urls import url


from .views import (StartupDetail, StartupList, 
                    TagDetail, TagList, TagPageList,
                    TagCreate, StartupCreate, NewsLinkCreate,
                    TagUpdate, StartupUpdate, NewsLinkUpdate,
                    TagDelete, StartupDelete, NewsLinkDelete,)


urlpatterns = [
    url(r'^newslink/create/$', NewsLinkCreate.as_view(), name='newslink_create' ),
    url(r'^newslink/update/(?P<pk>\d+)/$', NewsLinkUpdate.as_view(), name='newslink_update'),
    url(r'^newslink/delete/(?P<pk>\d+)/$', NewsLinkDelete.as_view(), name='newslink_delete'),

    url(r'^startup/$', StartupList.as_view(), name='startup_list'),
    url(r'^startup/create/$', StartupCreate.as_view(), name='startup_form_create'),
    url(r'^startup/(?P<slug>[\w\-]+)/$', StartupDetail.as_view(), name='startup_detail'),
    url(r'^startup/(?P<slug>[\w\-]+)/update/$', StartupUpdate.as_view(), name='startup_update'),
    url(r'^startup/(?P<slug>[\w\-]+)/delete/$', StartupDelete.as_view(), name='startup_delete'),

    url(r'^tag/$', TagList.as_view(), name='tag_list'),
    url(r'^tag/(?P<page_number>\d+)/$', TagPageList.as_view(), name='tag_page'),
    url(r'^tag/create/$', TagCreate.as_view(), name='tag_form_create'),
    url(r'^tag/(?P<slug>[\w\-]+)/$', TagDetail.as_view(), name='tag_detail'),
    url(r'^tag/(?P<slug>[\w\-]+)/update/$', TagUpdate.as_view(), name='tag_update'),
    url(r'^tag/(?P<slug>[\w\-]+)/delete/$', TagDelete.as_view(), name='tag_delete'),
]

suorganizer/suorganizer/urls.py
"""
Definition of urls for suorganizer.
"""

from django.conf.urls import include, url
from django.views.generic import RedirectView
from django.contrib import admin, auth
from django.contrib.auth import urls as auth_urls
from django.contrib.flatpages import urls as flatpages_urls
from .views import redirect_root
# admin.autodiscover()


urlpatterns = [
    # Examples:
    # url(r'^$', suorganizer.views.home, name='home'),
    # url(r'^suorganizer/', include('suorganizer.suorganizer.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', app_name='user', namespace='dj-auth')),
    url(r'^$', RedirectView.as_view(pattern_name='blog:post_list',permanent=False)),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^contact/', include('contact.urls')),
    #url(r'^page/', include(flatpages_urls)),
    url(r'^', include('organizer.urls', namespace='organizer', app_name='organizer')),
    url(r'^', include(flatpages_urls)),
]

suorganizer/organizer/models.py
from datetime import date

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    def published_post(self):
        return self.blog_post.filter(pub_date__lt=date.today())

    def get_absolute_url(self):
        return reverse('organizer:tag_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer:tag_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizer:tag_delete', kwargs={'slug': self.slug})


class Startup(models.Model):
    name         = models.CharField(max_length=31, db_index=True)
    slug         = models.SlugField(max_length=31, unique=True, help_text='A label for URL config')
    description  = models.TextField()
    founded_date = models.DateField(verbose_name='date founded')
    contact      = models.EmailField()
    website      = models.URLField(max_length=255)

    tags         = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'

    def published_posts(self):
        return self.blog_posts.filter(pub_date__lt=date.today())

    def get_absolute_url(self):
        return reverse('organizer:startup_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse('organizer:startup_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
        return reverse('organizer:startup_delete', kwargs={'slug': self.slug})


class NewsLink(models.Model):
    title    = models.CharField(max_length=63)
    pub_date = models.DateField(verbose_name='date published')
    link     = models.URLField(max_length=255)

    startup  = models.ForeignKey(Startup)

    def __str__(self):
        return "{}:{}".format(self.startup, self.title)

    class Meta:
        verbose_name  = 'news article'
        ordering      = ['-pub_date']
        get_latest_by = 'pub_date'

    def get_absolute_url(self):
        return self.startup.get_absolute_url()

    def get_update_url(self):
        return reverse('organizer:newslink_update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('organizer:newslink_delete', kwargs={'pk': self.pk})

suorganizer/organizer/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import NewsLink, Startup, Tag

class SlugCleanMixin:
    '''混入类用于添加clean_slug方法'''
    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()
        if new_slug == 'create':
            raise ValidationError('Slug may not be "create".')
        return new_slug


class NewsLinkForm(forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = '__all__'


class StartupForm(forms.ModelForm, SlugCleanMixin):
    class Meta:
        model = Startup
        fields = '__all__'


class TagForm(forms.ModelForm, SlugCleanMixin):
    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        return self.cleaned_data['name'].lower()

suorganizer/organizer/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View, CreateView, DetailView, DeleteView, UpdateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from user.decorators import class_login_required, require_authenticated_permission

from .models import Startup, Tag, NewsLink
from .forms import TagForm, StartupForm, NewsLinkForm
from .utils import ObjectUpdateMixin, ObjectDeleteMixin
# Create your views here.


class StartupDetail(DetailView):
    context_object_name = 'startup'
    model               = Startup
    template_name       = 'organizer/startup_detail.html'

    #def get(self, request, slug):
    #    startup = get_object_or_404(Startup, slug__iexact=slug)
    #    return render(request, 
    #                  'organizer/startup_detail.html',
    #                  {'startup': startup})


class TagDetail(DetailView):
    context_object_name = 'tag'
    model               = Tag
    template_name       = 'organizer/tag_detail.html'

    #def get(self, request, slug):
    #    tag = get_object_or_404(Tag, slug__iexact=slug)
    #    return render(request,
    #                  'organizer/tag_detail.html',
    #                  {'tag': tag})





class TagList(View):
    template_name = 'organizer/tag_list.html'

    def get(self, request):
        return render(request,
                      'organizer/tag_list.html',
                      {'tag_list': Tag.objects.all()})


class TagPageList(View):
    template_name = 'organizer/tag_list.html'
    paginate_by = 5

    def get(self, request, page_number): # 就获取page_number的方式有点小变化
        tags = Tag.objects.all()
        paginator = Paginator(tags, self.paginate_by)
        try:
            page = paginator.page(page_number)
        except PageNotAnInteger:
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages)
        
        prev_url = reverse('organizer:tag_page', args=[page.previous_page_number()]) if page.has_previous() else None
        next_url = reverse('organizer:tag_page', args=[page.next_page_number()]) if page.has_next() else None

        return render(request,
                      self.template_name,
                      {'tag_list': page, 'paginator': paginator, 
                       'next_page_url': next_url, 'previous_page_url': prev_url})


class StartupList(View):
    page_kwarg    = 'page'
    template_name = 'organizer/startup_list.html'
    paginate_by   = 3

    def get(self, request):
        startups    = Startup.objects.all()
        paginator   = Paginator(startups, self.paginate_by)
        page_number = request.GET.get(self.page_kwarg)
        try:
            page = paginator.page(page_number) 
        except PageNotAnInteger: # 这个page_number可能获取不到
            page = paginator.page(1)
        except EmptyPage:
            page = paginator.page(paginator.num_pages) # 请求页数过大返回最后一页的结果

        # DRY:生成当前请求页前后页的相关链接，并用到template中
        prev_url = '?{}={}'.format(self.page_kwarg, page.previous_page_number()) if page.has_previous() else None
        next_url = '?{}={}'.format(self.page_kwarg, page.next_page_number()) if page.has_next() else None
        
        return render(request,
                      self.template_name,
                      {'startup_list': page, 'paginator': paginator, 
                       'next_page_url': next_url, 'previous_page_url': prev_url})


@require_authenticated_permission('organizer.add_tag')
class TagCreate(CreateView):
    form_class    = TagForm
    template_name = 'organizer/tag_form_create.html'


class StartupCreate(CreateView):
    form_class    = StartupForm
    template_name = 'organizer/startup_form_create.html'


class NewsLinkCreate(CreateView):
    form_class    = NewsLinkForm
    template_name = 'organizer/startup_form_create.html'


class NewsLinkUpdate(View):
    form_class    = NewsLinkForm
    template_name = 'organizer/newslink_form_update.html'

    def get(self, request, pk):
        newslink = get_object_or_404(NewsLink, pk=pk)
        return render(request, 
                      self.template_name,
                      {'form': self.form_class(instance=newslink), 'newslink': newslink})

    def post(self, request, pk):
        newslink = get_object_or_404(NewsLink, pk=pk)
        bound_form = self.form_class(request.POST, instance=newslink)
        if bound_form.is_valid():
            new_newslink = bound_form.save()
            return redirect(new_newslink)
        else:
            return render(request, 
                          self.template_name,
                          {'form': bound_form, 'newslink': newslink})

@require_authenticated_permission('organizer.change_tag')
class TagUpdate(UpdateView):
    form_class    = TagForm
    model         = Tag
    template_name = 'organizer/tag_form_update.html'


@require_authenticated_permission('organizer.change_startup')
class StartupUpdate(UpdateView):
    form_class    = StartupForm
    model         = Startup
    template_name = 'organizer/startup_form_update.html'


class NewsLinkDelete(DeleteView):
    model = NewsLink

    def get_success_url(self):
        return self.object.startup.get_absolute_url()
    #def get(self, request, pk):
    #    newslink = get_object_or_404(NewsLink, pk=pk)
    #    return render(request, 'organizer/newslink_form_delete.html', {'newslink': newslink})

    #def post(self, request, pk):
    #    newslink = get_object_or_404(NewsLink, pk=pk)
    #    startup = newslink.startup
    #    newslink.delete()
    #    return redirect(startup)


class TagDelete(DeleteView):
    model         = Tag
    success_url   = reverse_lazy('organizer:tag_list')
    template_name = 'organizer/tag_form_delete.html'


class StartupDelete(DeleteView):
    model         = Startup
    success_url   = reverse_lazy('organizer:startup_list')
    template_name = 'organizer/startup_form_delete.html'

suorganizer/organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

{% load staticfiles %}
{% block head %}
    <link href="{% static 'organizer/style.css' %}" rel="stylesheet" />
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form_create.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{% url 'organizer:newslink_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Link Article</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete News Article
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ newslink.get_delete_url }}" method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete link to article {{ newslink.name }}?
                </p>
                <button type="submit">Delete Article Link</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update News Article
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ newslink.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Article Link</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - {{ startup.name }}
{% endblock %}

{% block content %}
    <article>
        <h2>{{ startup.name }}</h2>
        <ul>
            <li><a href="{{ startup.get_update_url }}">Edit Startup</a></li>
        </ul>
        {#展示公司基本信息#}
        <dl>
            <dt>Date Founded</dt>
                <dd>{{ startup.founded_date|date:"F jS, Y"}}</dd>
            <dt>Website</dt>
                <dd>{{ startup.website|urlize}}</dd>
            <dt>Contact</dt>
                <dd>{{ startup.contact}}</dd>
            <dt>Tag{{ startup.tags.count|pluralize }}</dt>
                {% for tag in startup.tags.all %}
                    <dd><a href="{{ tag.get_absolute_url }}">{{ tag.name|title }}</a></dd>
                {% endfor %}
        </dl>
        <p>{{ startup.description|linebreaks }}</p>

        {% if startup.newslink_set.all %}
        {#展示与公司相关的新闻链接#}
            <section>
                <h3>Recent News</h3>
                <ul>
                    {% for newslink in startup.newslink_set.all %}
                        <li>
                            <a href="{{ newslink.link }}">{{ newslink.title|title }}</a>
                            <ul>
                                <li><a href="{{ newslink.get_update_url }}">Edit Link</a></li>
                                <li><a href="{{ newslink.get_delete_url }}">Delete Link</a></li>
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}

        {% if startup.blog_posts.all %}
            {#展示与公司相关的博客推文#}
            <section>
                <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
                <ul>
                    {% for post in startup.blog_posts.all %}
                        <li><a href="{{ post.get_absolute_url }}">{{ post.title|title }}</a></li>
                    {% endfor %}
                </ul>
            </section>
        {% endif %}
    </article>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form_create.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{% url 'organizer:startup_form_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ startup.get_delete_url }}" method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete startup {{ startup.name }}?
                </p>
                <a href="{{ startup.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update Startup
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ startup.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Startup</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Startups
{% endblock %}

{% block content %}
    <h2>Startup List</h2>
    <div>
        <a href="{% url 'organizer:startup_form_create' %}">Create New Startup</a>
    </div>
    <ul>
        {% for startup in startup_list %}
            <li>
                <a href="{{ startup.get_absolute_url }}">{{ startup.name }}</a>
                <ul>
                    <li><a href="{{ startup.get_update_url }}">Edit Startup</a></li>
                    <li><a href="{{ startup.get_delete_url }}">Delete Startup</a></li>
                </ul>
            </li>
        {% empty %}
            <li><em>No Startups Avaiable</em></li>
        {% endfor %}
    </ul>
    {% if startup_list.has_other_pages %}
        <ul>
            {% if startup_list.has_previous %}
                <li><a href="{{ previous_page_url }}">Previous</a></li>
            {% endif %}
            <li>Page {{ startup_list.number }} of {{ paginator.num_pages }}</li>
            {% if startup_list.has_next %}
                {#<li><a href="?page={{ startup_list.next_page_number }}">Next</a></li>#}
                <li><a href="{{ next_page_url }}">Next</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block content %}
    <h2>{{ tag.name|title }}</h2>
    <ul>
        <li><a href="{{ tag.get_update_url }}">Edit Tag</a></li>
        <li><a href="{{ tag.get_delete_url }}">Delete Tag</a></li>
    </ul>
    {% if tag.startup_set.all %}
        <section>
            {#列出所有的Startups#}
            <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
            <p>
                Tag is associated with {{ tag.startup_set.count }} 
                startup{{ tag.startup_set.count|pluralize }}
            </p>
            <ul>
                {% for startup in tag.startup_set.all %}
                    <li><a href="{{ startup.get_absolute_url }}">{{ startup.name }}</a></li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}

    {% if perms.blog.view_future_post %}
      {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}
  {% else %}
      {% if tag.published_posts|length > 0 %}
        <section>
          <h3>Blog Post{{ tag.published_posts|pluralize }}</h3>
          <ul>
            {% for post in tag.published_posts %}
              <li><a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.startup_set.all and not tag.published_posts %}
        <p>This tag is not related to any content.</p>
      {% endif %}
  {% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form_create.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Create Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{% url 'organizer:tag_form_create' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Create Tag</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Delete Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ tag.get_delete_url }}" method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete tag {{ tag.name }}
                </p>
                <a href="{{ tag.get_absolute_url }}">Cancel</a>
                <button type="submit">Delete Tag</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
    {{ block.super }} - Update Tag
{% endblock %}

{% block content %}
    <div>
        <div>
            <form action="{{ tag.get_update_url }}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update Tag</button>
            </form>
        </div>
    </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer\base_organizer.html" %}

{% block title %}
    {{ block.super }} - Tag List
{% endblock %}

{% block content %}
    <h2>Tag List</h2>
    <div>
        <a href="{% url 'organizer:tag_form_create' %}">Create New Tag</a>
    </div>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{{ tag.get_absolute_url }}">{{ tag.name|title }}</a>
                <ul>
                    <li><a href="{{ tag.get_update_url }}">Edit Tag</a></li>
                    <li><a href="{{ tag.get_delete_url }}">Delete Tag</a></li>
                </ul>
            </li>
        {% empty %}
            <li><em>There are currently no Tags available.</em></li>
        {% endfor %}
    </ul>
    
    {% if tag_list.has_other_pages %}
        <ul>
            {% if tag_list.has_previous %}
                <li><a href="{{ previous_page_url }}">Previous</a></li>
            {% endif %}
            <li>Page {{ tag_list.number }} of {{ paginator.num_pages }}</li>
            {% if tag_list.has_next %}
                <li><a href="{{ next_page_url }}">Next</a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}